sudo: required

language: python

services:
    - docker

notifications:
  email:
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: false

before_install:
    - docker build -t mozilla-services/tokenserver .
    
script:
    - docker run mozilla-services/tokenserver /bin/sh -c "cd /app; nosetests tokenserver/tests"
