language: python

python:
 - "2.7"

services:
 - mysql

notifications:
  email:
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: false

install:
  - make install-dev

before_script:
  - mysql -e 'create database tokenserver_test;'

script:
  - make flake8
  - MOZSVC_SQLURI=pymysql://root@localhost/tokenserver_test make tests-once
  - make tests-once
